painted_rabbit.gemspec
With author information and web page.
=> Updated gemspec

README.md, circle.yml
~~First attempt to see if it can build successfully on circle ci~~
Settings and badge for circle ci.
=> Add circleci settings

MIT-LICENSE
To reflect the proper copyright holder
=> Update the license file

Gemfile, Gemfile.lock, README.md, Rakefile, blueprinter.gemspec, lib/blueprinter.rb, lib/blueprinter/base.rb, lib/blueprinter/blueprinter_error.rb, lib/blueprinter/field.rb, lib/blueprinter/serializer.rb, lib/blueprinter/serializers/association_serializer.rb, lib/blueprinter/serializers/public_send_serializer.rb, lib/blueprinter/version.rb, lib/blueprinter/view.rb, lib/blueprinter/view_collection.rb, lib/painted_rabbit.rb, lib/painted_rabbit/painted_rabbit_error.rb, lib/tasks/blueprinter_tasks.rake, test/active_record_test.rb, test/benchmarks/active_record_big_o_test.rb, test/benchmarks/active_record_ips_test.rb, test/benchmarks/big_o_test.rb, test/benchmarks/ips_test.rb, test/dummy/config/application.rb, test/painted_rabbit_test.rb, test/test_helper.rb
Rename all files, constants, variables, and strings to reflect the
name change to Blueprinter.
Resolves #19
=> Rename all things PaintedRabbit to Blueprinter

README.md
This is the readme to describe the changes made from #38.
=> Add readme for defining a field in the Blueprint

blueprinter.gemspec
=> Add description to gemspec

README.md
Show current version of gem via rubygem badge
=> Show current version of gem via rubygem badge

README.md
Fixing up the associations useage call to use the correct defined view.
=> Fix wrong view in associations example call.

Gemfile, Gemfile.lock, spec/benchmarks/active_record_big_o_test.rb, spec/benchmarks/active_record_ips_test.rb, spec/factories/model_factories.rb, spec/integrations/base_spec.rb
Thoughtbot has deprecated the FactoryGirl gem in favor of FactoryBot.
=> Changed FactoryGirl to FactoryBot

lib/blueprinter/base.rb, spec/integrations/base_spec.rb
=> 73 render as hash

README.md
This solves #88 by specifically documenting the `name` option.
=> Improve documentation for renaming fields

README.md
Add conditional fields to readme. It has been supported since 0.6.0
=> Update README.md with conditional fields

README.md
Just adding this readme here to remind ourselves of the version bump process.
=> Update readme on how to release new versions

Rakefile, lib/blueprinter/field.rb, spec/factories/model_factories.rb, spec/integrations/base_spec.rb
- Enable warnings in rspec so that these do not go under the radar
- Use `defined?`
- Use dynamic attributes in factories
- Remove unused variables
Not sure if I should have enabled errors in rspec. Let me know if I should change this
=> Fix warnings

CHANGELOG.md, lib/blueprinter/helpers/base_helpers.rb, lib/blueprinter/version.rb
Based on our discussions on gitter, removing include_associations
=> remove include_associations

lib/blueprinter/base.rb
Please squash + merge when approved.
=> Fix Transformer example

CHANGELOG.md, README.md, lib/blueprinter/version.rb
* 🚀 [FEATURE] Ability to include multiple views in a single method call with `include_views`. [184](https://github.com/procore/blueprinter/pull/184). Thanks to [@narendranvelmurugan](https://github.com/narendranvelmurugan).
* 💅 [ENHANCEMENT] Update field-level conditional settings to reflect new three-argument syntax. [183](https://github.com/procore/blueprinter/pull/183). Thanks to [@danirod](https://github.com/danirod).
* 💅 [ENHANCEMENT] Modify Extractor access control in documentation. [182](https://github.com/procore/blueprinter/pull/182). Thanks to [@cagmz](https://github.com/cagmz).
* 💅 [ENHANCEMENT] Fix the Transformer example documentation. [174](https://github.com/procore/blueprinter/pull/174). Thanks to [@tjwallace](https://github.com/tjwallace).
=> Draft release for v0.20.0

lib/blueprinter/base.rb, lib/blueprinter/extractor.rb, lib/blueprinter/field.rb, lib/blueprinter/transformer.rb, lib/blueprinter/version.rb, lib/blueprinter/view.rb, spec/benchmarks/active_record_big_o_test.rb
Hi 
This PR just fixes some rubocop issues
=> Rubocop Checks

CHANGELOG.md, lib/blueprinter/version.rb
Version bump to introduce rails generator
=> Bump to 0.22.0

README.md, lib/blueprinter/base.rb, lib/blueprinter/configuration.rb, lib/blueprinter/extractors/association_extractor.rb, spec/integrations/shared/base_render_examples.rb, spec/units/configuration_spec.rb
This is a fix for #178.
Since I've never personally needed this, I'm afraid the example added to README.md does not do a great job motivating why to use this feature. I'm open to suggestions or edits.
=> Configure extractor

CHANGELOG.md, lib/blueprinter/version.rb
=> Bump 0.23.1

lib/blueprinter/view_collection.rb, spec/integrations/shared/base_render_examples.rb
=> fix field exclusion for views

CHANGELOG.md, lib/blueprinter/version.rb
=> Bump to 0.23.3

CHANGELOG.md, lib/blueprinter/version.rb
release 0.25.1 which contains #233
=> bump version 0.25.1

lib/blueprinter/view_collection.rb, spec/integrations/base_spec.rb, spec/integrations/shared/base_render_examples.rb
=> Fixes include_view order to make field/association redefinition works

catalog-info.yaml
Fixing the Backstage catalog to include the System
=> Devprod 98/ecosystem division

.github/CODEOWNERS, README.md
=> fix: add CODEOWNERS

.github/CODEOWNERS, README.md
- add section in readme to update remote url
Checklist:
=> chore: update CODEOWNERS to new procore-blueprinter team

.github/CODEOWNERS
=> chore: file requires team name to include org

EMERITUS.md
After speaking with Philip he has asked to be moved to Emeritus.
We thank him for his contributions.
Checklist:
=> chore: add Philip Q Nguyen to emeritus

EMERITUS.md, blueprinter.gemspec
=> chore: move Derek Carter (dlcarter) to emeritus

.github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yaml
=> fix: dependabot labelling

spec/spec_helper.rb
Testing CodeQL to ensure it is working properly.
=> removed test comment

CHANGELOG.md, lib/blueprinter/version.rb
Checklist:
- Updates `CHANGELOG` and increments a PATCH version.
=> Release v1.1.1

CHANGELOG.md, lib/blueprinter/version.rb
=> Release v1.1.2

.gitignore, lib/blueprinter/base.rb, spec/integrations/shared/base_render_examples.rb
=> Explicitly Cast Field/Association method argument to Symbol

lib/blueprinter/blueprint_validator.rb
Fixes Rubocop "Style/RedundantCondition", which is blocking other PRs.
=> Make Rubocop happy
