- Gemfile
- Gemfile.lock
- lib/painted_rabbit.rb
- lib/painted_rabbit/base.rb
- lib/painted_rabbit/serializer.rb
- lib/painted_rabbit/serializers/association_serializer.rb
- painted_rabbit.gemspec
- test/active_record_test.rb
- test/dummy/app/models/user.rb
- test/dummy/app/models/vehicle.rb
- test/dummy/db/migrate/20170809211229_create_users.rb
- test/dummy/db/migrate/20170830212110_create_vehicles.rb
- test/dummy/db/schema.rb
- test/factories/model_factories.rb
- test/painted_rabbit_test.rb
- test/rails_test_helper.rb
- test/test_helper.rb
*What this PR accomplishes:*
* Support for nested serializers & views for associations
e.g. `association :vehicles, serializer: VehicleViewSerializer, view: :extended`
* Extended tests for associations and Active Record lookups
* Removes ActiveRecord as a foundational requirement for the serializer
* Removes our dependency on ActiveRecord for the base serializer tests, greatly speeding them up
> ActiveRecord/Association Tests & Support

- lib/painted_rabbit/base.rb
- lib/painted_rabbit/serializer.rb
- lib/painted_rabbit/serializers/association_serializer.rb
- lib/painted_rabbit/serializers/public_send_serializer.rb
- test/painted_rabbit_test.rb
Simplifies the logic of field serializers, placing all the magic into a method (that must be implemented) called `serializer`
We had a confusing interface for field serializers implementing their logic in a `&block` and then relying on `bleh` and `blah` to implement.
> Refactors serializers to be simpler and avoid need for blehs and blahs

- lib/painted_rabbit/base.rb
- lib/painted_rabbit/view.rb
- lib/painted_rabbit/view_collection.rb
- test/active_record_test.rb
- test/painted_rabbit_test.rb
This PR changes the format of defining views from:
```ruby
identifier :id
field :name
include_in [:normal, :extended] do
field :description
end
include_in :extended do
field :color
end
```
to
```ruby
identifier :id
field :name
view :normal do
field :description
end
view :extended do
incldue_view :normal
field :color
end
```
And also implements the ability to exclude fields from views using the interface `exclude :field_name`
> Implement an improved View interface

- Rakefile
- circle.yml
- test/benchmarks/active_record_big_o_test.rb
- test/benchmarks/active_record_ips_test.rb
- test/benchmarks/benchmark_helper.rb
- test/benchmarks/big_o_test.rb
- test/benchmarks/ips_test.rb
There are two types of tests; an iterations per second (IPS) test, and a test to see if increasing number of objects passed to `Base#self.render` increases execution time linearly.
We consider both `ActiveRecord` objects and simple objects (`OpenStruct`) when making the tests.
In the IPS tests, we assume that `ActiveRecord` objects will iterate at least 2500 times per second, and an `OpenStruct` object will iterate at least 3000 times per second. Otherwise, the test will fail.
Benchmark tests also only run if you type `bundle exec rake benchmarks`. Default rake will not run the benchmarks.
To see results, open up circle ci, and view the rake benchmarks logs.
> Benchmark tests #7

- lib/painted_rabbit/painted_rabbit_error.rb
Accessing a module through the shorthand method works only if the
module has already been loaded previously. It will NOT define the
module which could easily lead to Uninitialized Constants errors.
Basically, if painted_rabbit_error.rb was loaded first into memory,
it will raise an exeption because the PaintedRabbit module was not
defined.
Our test has not been loading this file first, so we have not
encountered any errors. However, if you wanted to manually require
painted_rabbit.rb into an IRB session, it will erorr.
This long form will fix that and define the PaintedRabbit module if it
has not been loaded.
> Use long form style of accessing modules

- Gemfile.lock
- painted_rabbit.gemspec
JSON should be a runtime dependency and not just a development
dependency.
We are using required keyword arguments in a number of places
which is a ruby 2.1+ feature.
Additionally, we are using ruby 2.2.2 and above libraries in development
so to stay safe, we will require ruby 2.2.2 in the gemspec.
> Gemspec fix

- README.md
Due to #23, we now need to use new circleci badge that points to the new repo name.
> Update circleci badge to use new name

- lib/blueprinter/base.rb
- lib/blueprinter/optimizer.rb
Add `Optimizer` to query `ActiveRecord::Relation`
1. detect for `ActiveRecord::Relation` instead of `ActiveRecord::Base`
objects for the time being since all the optimization methods we are
doing are actually `ActiveRecord::Relation` methods and not
`ActiveRecord::Base` methods.
2. Move all optimization related methods to it's own class, `Optimizer`
Resolves #8
> Add Optimizer to query ActiveRecord::Relation

- .gitignore
- Gemfile.lock
- blueprinter.gemspec
- lib/blueprinter/base.rb
Resoves #14 
Add Yard gem for documentation. Yard is what parses the yard tags and serves the
documentation. Yard is what powers rubydoc.info. 
Also documented the `Base.render` method as the first documented method using yard.
Yard is added in development runtime as it is only to be used in
development.
Official website of yard: https://yardoc.org/
yard github: https://github.com/lsegal/yard
We will eventually use http://rubydoc.info to make the docs available online.
In order to view docs in development: 
1. execute `yardoc` to generate docs
2. execute `yard server -r` to serve the docs from localhost:8808
3. navigate your browser to localhost:8808
> Setup Yard - Rubydoc

- Gemfile.lock
- blueprinter.gemspec
Allow us to use `binding.pry` while in development to help us debug.
> Add pry for debugging in development

- README.md
- lib/blueprinter/base.rb
- lib/blueprinter/field.rb
- lib/blueprinter/optimizer.rb
- lib/blueprinter/serializer.rb
- lib/blueprinter/view.rb
- lib/blueprinter/view_collection.rb
- Adds yard inline docs to the public methods
- Mark private methods that are visible private. Marking them private warns devs not to use it as those methods could change any time and without warning.
The best way to see the docs is to:
1. bring the branch down locally.
2. `yard server -r`
3. Navigate to localhost:8808
#26
> Document methods

- lib/blueprinter/serializers/association_serializer.rb
- test/active_record_test.rb
options[:serializer] should be options[:blueprint]
When working with an association, we expect end developers to create
their own blueprint and pass it as an option like so:
`association :vehicles, blueprint: VehicleBlueprint `.
Previously calling the option `:serializer` was incorrect.
resolves #34
> Rename serializer option to blueprint

- lib/blueprinter/base.rb
- lib/blueprinter/serializers/block_serializer.rb
- lib/blueprinter/serializers/local_method_serializer.rb
- test/active_record_test.rb
- test/blueprinter_test.rb
Resolves #32
~Add a method call `local_method`.  `local_method` accepts a method name and a method body. The method name is passed as an argument, and the method body is passed into a block.~
~Why we need something like this? There are situations where end devs want to define a method that are not used anywhere else except to have it serialized into JSON.~
Usage:
```ruby
identifier :id
fields :name
local_method :age { 30 + 1 }
end
```
~So currently this works. But I also just now realized that it's use cases are currently narrow without first tackling #33. #33 would allow end developers to pass in custom options from `render` and utilize that in their blueprint class.~
Update: 10/20
~Now object is passed into the block so you can use it like so:~ …
> Add local methods

- README.md
- circle.yml
- test/active_record_test.rb
- test/blueprinter_test.rb
Prior to 2.4, Ruby does not handle mixing block arguments with regular arguments
WITHOUT parens correctly. Ideally, our DSL would look like:
```ruby
field :name { |obj| ... }
```
but <2.4 reads this like
```ruby
field(:name); { |obj ... }
```
finishing the method call before the block is even considered.
> Conform tests to Ruby 2.2.2

- README.md
- lib/blueprinter/base.rb
- lib/blueprinter/serializer.rb
- lib/blueprinter/serializers/association_serializer.rb
- lib/blueprinter/serializers/block_serializer.rb
- lib/blueprinter/serializers/public_send_serializer.rb
- test/active_record_test.rb
- test/blueprinter_test.rb
Allow `render` to take an options hash.
This `options` hash is internally called `local_options`, and it is
passed through to the serializer. 
I wanted to clearly distinguish options passed in through render, and the previously used options that was stored in Field. So i named the options passed in by render as `local_options`.
End devs can now pass an options hash to `render` and use it in the `field` block like this:
```ruby
field :company_id {|obj, options| options.company.id }
end
UserBlueprint.render(user, company: company)
#=> {"uuid": "x2334fw987a", "company_id": 2}
```
> Render with options

- test/benchmarks/active_record_ips_test.rb
- test/benchmarks/ips_test.rb
Previously, we were building and running benchmarks on circle ci using
ruby 2.4.1. We now build and run benchmarks on 2.2.2. Ruby 2.2.2 is
slower than 2.4.1, so we need to reduce the IPS benchmarks. Otherwise, we
would get benchmark failures too regularly.
> IPS are slower due to ruby downgrade.

- lib/blueprinter/base.rb
It should be `PublicSendSerializer` and not `AssociationSerializer`. While both works, `PublicSendSerializer` is more efficient and was made for this use case.
Resolves #30
> Fix default serialzer for `Base.field`

- Gemfile.lock
- blueprinter.gemspec
Due to a security vulnerability in yard < 0.9.11, bumps the yard version to ~> 0.9.11
> Update yard version for security

- Gemfile.lock
- README.md
- blueprinter.gemspec
- lib/blueprinter.rb
- lib/blueprinter/base.rb
- lib/blueprinter/configuration.rb
- spec/units/configuration_spec.rb
The goal of this PR is to allow developers to utilize Oj to generate the JSON. This is to resolve issue #17. I would love some careful eyes on this, ideas, opinions.
You will notice that I removed the JSON gem dependency. That is done because the JSON gem and the subsequent `require 'json'` will override core ruby classes to add the `to_json` method. The override is global and it will affect everything in the developer's project. If the developer had already overridden classes with their own `to_json`, then we do not want to override that.
Instead, it is up to the developer to decide whether they want to use the JSON gem or Oj. Once they have installed and required the JSON gem or the Oj gem, they can configure Blueprinter to use whichever one of those:
```ruby
Blueprinter.configure do …
```
> Configurable json generator

- lib/blueprinter/base.rb
- lib/blueprinter/field.rb
- lib/blueprinter/helpers/active_record_helpers.rb
- lib/blueprinter/optimizer.rb
- lib/blueprinter/serializers/auto_serializer.rb
- lib/blueprinter/serializers/hash_serializer.rb
- spec/integrations/base_spec.rb
- spec/integrations/shared/base_render_examples.rb
Support Hash by using AutoSerializer as default
AutoSerializer will delegate between HashSerializer to serialize
Hash objects or to PublicSendSerializer to serialize objects with
dot notation attributes.
We also don't iterate over all objects that respond to `:map` anymore
because `Hash` responds to `:map`, but we wouldn't want that. So we
have to be more specific on what objects we treat like an array.
In the process of creating new serializers, I noticed that the Base class seems to know about Field and the Serializer class way too much. So I move the responsibility of invoking
the serializer to the Field. This actually resolves #43.
> Support hash object passed to render

- README.md
Added link to doc and replaced the duplicated "Documentation" heading with
a more appropriate heading.
> Add link to doc

- spec/benchmarks/benchmark_helper.rb
Past benchmark tests have shown that block.call is almost two times
slower than yield in older versions of Ruby.
> Change 'block.call to yield'

- CHANGELOG.md
- README.md
- lib/blueprinter/extractors/association_extractor.rb
- lib/blueprinter/version.rb
- spec/integrations/base_spec.rb
**Included in the PR**
For models that have `belongs_to` association that allow `null` relationship, blueprinter serializes to `null` by default. This PR adds an ability to add a `default` option to blueprinter association which can be used as the serialized value instead of null.
In cases when the association `company` is `nil`, the behavior looks as follows:
**Before**
```ruby
association :company, blueprint: CompanyBlueprint
end
```
`UserBlueprint.render(user)` renders `{ "id": 1, "company": null }`
**After**
```ruby
association :company, blueprint: CompanyBlueprint, default: {}
end
```
`UserBlueprint.render(user)` renders `{ "id": 1, "company": {} }`
> Accept an option 'default' to allow setting default serialized value for association if null

- lib/blueprinter/base.rb
- lib/blueprinter/field.rb
- spec/integrations/shared/base_render_examples.rb
See https://github.com/procore/blueprinter/issues/81
One omission: methods should be declared before field declaration using them, i. e.
```ruby
class UserBlueprinter < Blueprinter::Base
def my_method(user, options)
end
field :first_name, if: :my_method
end
```
because methods are not available yet at field declaration time and I'm resolving Symbol to Method there. Is it worth fixing or I should just add a note to README?
Other one: AFAICS collection serialization is not tested at the moment, so I also skipped it.
> Add conditional fields support

- README.md
- lib/blueprinter/base.rb
- lib/blueprinter/extractors/auto_extractor.rb
- lib/blueprinter/extractors/datetime_extractor.rb
- spec/dummy/db/schema.rb
- spec/factories/model_factories.rb
- spec/integrations/base_spec.rb
- spec/integrations/shared/base_render_examples.rb
Blueprinter needs a mechanism to specify custom serialization for Date and DateTime fields.
To define a custom format for a Date or DateTime field, include the option `datetime_format` with the associated `strptime` format.
Usage:
```ruby
identifier :name
field :birthday, datetime_format: "%m/%d/%Y"
end
```
Output:
```json
{
"name": "John Doe",
"birthday": "03/04/1994"
}
```
> Add custom date and time formatting

- lib/blueprinter/base.rb
- lib/blueprinter/view.rb
- lib/blueprinter/view_collection.rb
- spec/integrations/base_spec.rb
- spec/units/view_spec.rb
Enable field and view definitions on superclasses
to be used by subclasses:
class ApplicationBlueprint < Blueprinter::Base
identifier :id
field :created_at
end
class PersonBlueprint < ApplicationBlueprint
fields :name, :age
end
Objects rendered with `PersonBlueprint` will contain fields `id`,
`created_at`, `name`, and `age`.
(Addresses issue #80)
> Inherit view definition when using inheritance

- README.md
- lib/blueprinter/base.rb
- lib/blueprinter/extractor.rb
- lib/blueprinter/extractors/association_extractor.rb
- lib/blueprinter/extractors/auto_extractor.rb
- lib/blueprinter/extractors/block_extractor.rb
- spec/integrations/base_spec.rb
Addresses #90.
I removed an extra hash from `BlockExtractor`. Not sure if should have, but it seemed to be redundant, and tests are passing.
I changed `AssociationExtractor` so that it accepts a nested extractor. This allowed me to reuse `AutoExtractor` and `BlockExtractor`, making `#association` now very similar to `#field`.
I noticed that we're passing classes as extractors, and that the class method `extract` always creates a new instance of itself. This will probably create an unnecessary number of objects. Instantiating them directly in `#field` and `#association` might help improve performance. I addressed that in this PR as well.
> Allow associations to be defined with a block

- README.md
- lib/blueprinter/base.rb
The blocks are yielded both the object and the options that were passed
to render. This commit simply ensure that the docs reflects that.
> Update docs regarding the args yielded to blocks

- README.md
- lib/blueprinter/base.rb
- lib/blueprinter/extractors/association_extractor.rb
- lib/blueprinter/extractors/auto_extractor.rb
- spec/integrations/base_spec.rb
Now that `::association` and `::field` receive an optional block,
`::identifier` should receive it as well.
Since all three methods receive an optional block, the block extraction
mechanism was moved to `AutoExtractor`. Removing this mechanism from
each individual method made them very similar. `::association` now uses
`::field` instead of directly adding the field to the current view.
Addresses #109
> Allow identifiers to be defined with a block

- lib/blueprinter/extractor.rb
This private flag was accidentally placed at the top level module,
causing many methods and classes set at the top level to be considered
private when it shouldn't have been.
Take a look at https://www.rubydoc.info/gems/blueprinter/Blueprinter
it has the `configure` method as private, when it should be public.
Moving this private flag down to the Extractor class level should
fix this.
> Localize private flag to class and not module

- lib/blueprinter/base.rb
Base.associations is not being used outside of Base, and should
not be exposed.
> Base.associations should be completely private

- README.md
- lib/blueprinter/extractors/association_extractor.rb
- lib/blueprinter/extractors/auto_extractor.rb
- spec/integrations/shared/base_render_examples.rb
**Included in the PR**
For fields that have a value of nil, blueprinter serializes to `null` by default. This PR adds an ability to add a `default` option to blueprinter fields which can be used as the serialized value instead of null.
**Before**
```ruby
field :first_name
end
```
`UserBlueprint.render(user)` renders `{ "id": 1, "first_name": null }`
**After**
```ruby
field :first_name, default: "N/A"
end
```
`UserBlueprint.render(user)` renders `{ "id": 1, "first_name": "N/A" }`
Aims to address: https://github.com/procore/blueprinter/issues/114
> Accept an option 'default' to allow setting default serialized field value if null

- CHANGELOG.md
- README.md
- lib/blueprinter/base.rb
- lib/blueprinter/configuration.rb
- lib/blueprinter/version.rb
- lib/blueprinter/view_collection.rb
- spec/integrations/base_spec.rb
- spec/units/configuration_spec.rb
1. Added a `render_as_json` API - When you want a JSONified hash - useful when you want to modify the generated hash but require it to be JSONified 
2. Added a configuration option to make sorting optional - for those who don't want to sort the fields by name but want it in the order it was defined. Bonus - adds a perf benefit. 
3. Update readme with latest updates and some missing public API specs like `render_as_hash`, `exclude`..
> render_as_json, making sorting fields optional

- CHANGELOG.md
- README.md
- lib/blueprinter/configuration.rb
- lib/blueprinter/extractors/association_extractor.rb
- lib/blueprinter/extractors/auto_extractor.rb
- lib/blueprinter/version.rb
- spec/integrations/base_spec.rb
- spec/integrations/shared/base_render_examples.rb
- spec/units/configuration_spec.rb
Previously we only supported being able to set default values at the field/association level. This PR enables setting a global default for all fields/associations that evaluate to nil.
```ruby
Blueprinter.configure do |config|
config.field_default = "N/A"
config.association_default = {}
end
```
```ruby
view :normal do
field :first_name, default: "N/A"
association :company, blueprint: CompanyBlueprint, default: {}
end
end
```
The default value specified at the field/association level will override the value specified in the global config.
> Add global default field/association value configuration.

- CHANGELOG.md
- lib/blueprinter/extractors/hash_extractor.rb
- lib/blueprinter/version.rb
- spec/activerecord_helper.rb
- spec/factories/model_factories.rb
- spec/integrations/base_spec.rb
- spec/integrations/shared/base_render_examples.rb
Proposed fix for #130 
Currently blueprinter does not serialize boolean `false` values, returning `null` instead
- Add a test to confirm the behavior is absent in the existing code, add a boolean attribute to the specs and add a specific context block for confirming the behavior of various data types
- Remove the offending OR operation, which appears unnecessary as there does not appear to be any type checking of object keys elsewhere.
> [Bugfix] Serialize boolean false values

- .circleci/config.yml
As part of this, I've configured our CircleCI to use the appropriate git ssh key and this sets the git configuration to use our CircleCI bot to tag the releases.
> Set git config settings for releasing as bot account.

- CHANGELOG.md
- lib/blueprinter/extractors/association_extractor.rb
- lib/blueprinter/version.rb
All credit for this fix goes to @checkbutton https://github.com/checkbutton
who opened up the original PR: https://github.com/procore/blueprinter/pull/136
Needing to get this in soon and couldn't merge changes into his personal branch -- so creating a new PR with those changes.
Thanks again @checkbutton 🎉
> Remove usage of Rails specific method Hash::except

- CHANGELOG.md
- README.md
The README is getting quite large, this makes things a lot cleaner by making the Usage instruction sections all collapsible and some other general reorganization. This keeps the basic usage sections open by default (still collapsible) though to provide quick usage instructions at a glance.
i.e.
<details open>
<summary>Basic</summary>
---
If you have an object you would like serialized, simply create a blueprint. Say, for example, you have a User record with the following attributes `[:uuid, :email, :first_name, :last_name, :password, :address]`.
You may define a simple blueprint like so:
```ruby
fields :first_name, :last_name, :email
end
```
and then, in your code:
```ruby
puts UserBlueprint.render(user) # Output is a JSON string …
```
> Cleanup README and make Usage Instructions Collapsible

- lib/blueprinter/base.rb
- lib/blueprinter/view.rb
- spec/units/view_spec.rb
@mcclayton , For derived views with multiple included views, ability to exclude multiple fields inline.
> exclude multiple fields inline

- CHANGELOG.md
- README.md
- lib/blueprinter/version.rb
- spec/integrations/shared/base_render_examples.rb
Release for version `0.16.0` which includes PR: [#141](https://github.com/procore/blueprinter/pull/141)
* 🚀 [FEATURE] Add ability to exclude multiple fields inline using `excludes`. [#141](https://github.com/procore/blueprinter/pull/141). Thanks to [@pabhinaya](https://github.com/pabhinaya).
> v0.16.0 Release

- lib/blueprinter/base.rb
- spec/integrations/base_spec.rb
I have the following use case (code simplified for readability):
```ruby
class ApplicationSerializer < Blueprinter::Base
def self.association(method, options = {}, &block)
super(
method,
{ blueprint: BlueprinterFinder.find(method) }.merge(options),
)
end
end
class UserSerializer < ApplicationSerializer
association :contents do |user, options|
if options[:version]
user.content_versions.find_by!(version: options[:version])
else
user.content_versions.last
end
end
end
class UsersController
def show
render json: UserSerializer.render(User.find(params[:id]), version: params[:version])
end
end
```
I also needed something like the following:
```ruby
class CredentialSerializer < ApplicationSerializer
association :user # pass in credential.version to UserSerializer#render somehow
end
class …
```
> Add :extractor option to ::association

- CHANGELOG.md
- lib/blueprinter/version.rb
v0.17.0 Release introducing the following changes:
* 🐛 [BUGFIX] Fixing view: :identifier including non-identifier fields. [#154](https://github.com/procore/blueprinter/pull/154). Thanks to [@AllPurposeName](https://github.com/AllPurposeName).
* 💅 [ENHANCEMENT] Add ability to override :extractor option for an ::association. [#152](https://github.com/procore/blueprinter/pull/152). Thanks to [@hugopeixoto](https://github.com/hugopeixoto).
> v0.17.0 Release

- .circleci/config.yml
Ruby 2.2 performance is not reliable, and it regularly fails the
blueprinter benchmark. We still support ruby 2.2 officially, but
can't be confidence in its performance.
We still are running benchmarks on 2.3, 2.4, and 2.5
> Dont run benchmarks for ruby 2.2

- CHANGELOG.md
- README.md
- lib/blueprinter/version.rb
* 🚀 [FEATURE] Added ability to specify transformers for Blueprinter views to further process the resulting hash before serialization. [#164](https://github.com/procore/blueprinter/pull/164). Thanks to [@amalarayfreshworks](https://github.com/amalarayfreshworks).
<details>
<summary>Transform Classes</summary>
---
Blueprinter provides the ability to specify `transform`s on views, which enable further
processing and transforming of resulting view field hashes prior to serialization.
Use `transform` to specify one transformer to be included for serialization.
A transformer is a class, extending `Blueprinter::Transformer` and implementing the `transform` method.
Whatever is returned from this `transform` method will end up being the resulting hash passed to serialization.
Create a Transform …
> Draft release for v0.19.0

- lib/blueprinter/extractor.rb
- lib/blueprinter/extractors/association_extractor.rb
- lib/blueprinter/extractors/auto_extractor.rb
- lib/blueprinter/extractors/block_extractor.rb
- lib/blueprinter/extractors/hash_extractor.rb
- lib/blueprinter/extractors/public_send_extractor.rb
Custom Extractor classes are already being used in production and the Private API warning in the docs is confusing for developers.
https://www.rubydoc.info/gems/blueprinter/Blueprinter/Extractor
Also makes prebuilt classes inheriting from Extractor private (from a [previous PR comment](https://github.com/procore/blueprinter/pull/165#issuecomment-532896106)).
> Modify Extractor access control

- README.md
The docs were not updated to reflect that both if and unless now expect three arguments for the conditional proc, even in the field settings. Passing two arguments as the previous version of the docs propose will yield a deprecation notice. This commit updates the docs so that it indicates how to use the three version argument.
Closes #179
> docs: update field-level conditional settings

- lib/blueprinter/base.rb
- lib/blueprinter/view.rb
- spec/units/view_spec.rb
Created a new method called include_views and pass multiple views as arguments, which will render all the passed views in the blueprint.  
before:
```
include_view :user_summary
include_view :org_summary
```
Now:
```
include_views :user_summary,  :org_summary
```
> Ability to include multiple views in a single method call

- lib/blueprinter/base.rb
- lib/blueprinter/view.rb
- lib/blueprinter/view_collection.rb
- spec/integrations/shared/base_render_examples.rb
This is a fix for #172.  Thanks to https://github.com/procore/blueprinter/pull/185 I saw that the problem comes from how fields are merged at render time. Hash insertion order was not quite enough but probably could have been made to work with some more bookkeeping during the field definition which would then be taken account of in ```ViewCollection``` ```#sortable_fields```and ```#merge_fields```
Rather than increasing the amount of fancy footwork involved with merging hashes, each ```View``` now builds up an ordering at definition time which is traversed at render time.
One edge case to note, is that if for some reason a ```View``` is defined over multiple block yields, the output order will be as if all those fields were added inside the first one. This seems no worse than the current …
> explicitly track field definition order when used to sort output fields

- lib/blueprinter/view_collection.rb
- spec/integrations/shared/base_render_examples.rb
This PR fails at this moment I was hoping someone could help me debug why it fails.
> Setting view causes state change on default view

- CHANGELOG.md
- lib/blueprinter/version.rb
**Patch Release 0.23.2**
* 🚀 [BUGFIX] Fixes issue where fields "bled" into other views due to merge side-effects. Resolved issue [205](https://github.com/procore/blueprinter/issues/205) in [#204](https://github.com/procore/blueprinter/pull/204) by [@trevorrjohn](https://github.com/trevorrjohn).
> Bump 0.23.2

- blueprinter.gemspec
Connected with https://github.com/procore/blueprinter/pull/208
> set rspec-rails <= 4.0 to support ruby 2.2

- CHANGELOG.md
The Year for all 0.23.* releases but the 0.23.4 release is 2019 but it should be 2020.
> Fix Changelog timestamps

- CHANGELOG.md
- README.md
- lib/blueprinter/extractors/association_extractor.rb
- lib/blueprinter/field.rb
- lib/blueprinter/version.rb
- spec/integrations/base_spec.rb
Enable passing options from one Blueprint to another via an association.
For example:
```ruby
class VehicleBlueprint < Blueprinter::Base
field :full_name do |vehicle, options|
"#{vehicle.model} #{options[:trim]}"
end
end
class DriverBlueprint < Blueprinter::Base
view :normal do
fields :first_name, :last_name
association :vehicles, blueprint: vehicle_blueprint, options: { trim: 'LX' }
end
end
```
> Enable passing options between blueprints via associations.

- README.md
- lib/blueprinter/configuration.rb
- lib/blueprinter/view.rb
- spec/integrations/shared/base_render_examples.rb
- spec/units/configuration_spec.rb
- spec/units/view_spec.rb
> Allow for defining default transformer

- CHANGELOG.md
- lib/blueprinter/version.rb
* 🚀 [FEATURE] Enable default `Blueprinter::Transformer`s to be set in the global configuration. [#222](https://github.com/procore/blueprinter/pull/222). Thanks to [@supremebeing7](https://github.com/supremebeing7).
> Release version 0.25.0

- CHANGELOG.md
- README.md
- lib/blueprinter/base.rb
- lib/blueprinter/configuration.rb
- lib/blueprinter/deprecation.rb
- lib/blueprinter/empty_types.rb
- lib/blueprinter/field.rb
- lib/blueprinter/version.rb
- spec/integrations/shared/base_render_examples.rb
- spec/units/configuration_spec.rb
- spec/units/deprecation_spec.rb
Adding in a class for managing deprecations and introducing a deprecation configuration option to the blueprinter config.
Deprecations can be set to the following behavior options:
When functionality in Blueprinter is invoked, that has been deprecated, the default behavior is to
write a deprecation notice to stderror.
However, deprecations can be configured to report at three different levels:
|        Key        |                              Result                             |
|:-----------------:|:---------------------------------------------------------------:|
| `:stderr` (Default) | Deprecations will be written to stderror                        |
| `:raise`            | Deprecations will be raised as `Blueprinter::BlueprinterError`s |
| `:silence`          | Deprecations will be …
> Add class for managing deprecations

- CHANGELOG.md
- lib/blueprinter/version.rb
* 🐛 [BUGFIX] Fixes issue where fields and associations that are redefined by later views were not properly overwritten. See [#201](https://github.com/procore/blueprinter/pull/201) thanks to [@Berardpi](https://github.com/Berardpi).
> Release version 0.25.3

- README.md
Identifier fields were only documented in the code base which has led to some confusion. This PR adds a section on `identifier`s in the README.
> Document identifiers in README

- catalog-info.yaml
Team name change from `team-ecosystem-core` to `team-developer-marketplace-experience`.
> Devprod 98/ecosystem division

- README.md
- blueprinter.gemspec
change from github.com/procore/blueprinter to github.com/procore-oss/blueprinter
Checklist:
> fix: github url in files

- CHANGELOG.md
- lib/blueprinter/version.rb
Release 0.26.0 to drop ruby < 2.7 support
This releases the gem to 0.26.0. It drops support for any ruby version less than 2.7. See #307
> Release 0.26.0 to drop ruby < 2.7 support

- .github/workflows/release.yaml
> fix: change release github action to use different actions

- .github/workflows/release.yaml
- blueprinter.gemspec
> fix: release fixes

- .github/workflows/release.yaml
> fix: actually build the gem file for releases

- .github/CODEOWNERS
- Adds @ritikesh to CODEOWNERS fiile. 
Checklist:
> [chore] Add ritikesh to CODEOWNERS

- README.md
We currently have a link to a Gitter forum in the README that's not intentionally used/maintained at the moment. While we're still discussing community communication options moving forward, we'd like to remove the link to avoid any confusion until a decision can be made. 
- Removes Gitter link from README
Checklist:
> Removes Gitter Link from README

- .github/workflows/stale.yaml
We are actively working through issues and pull requests.
Once done, we can add this and allow for automation of issues/PRs being marked stale/closed
Checklist:
> chore: add stale github action

- README.md
- Add invite link to #blueprinter Discord channel in README. 
Checklist:
> Add Discord Link to README

- .github/workflows/auto-assign-author.yaml
- .github/workflows/release.yaml
- .github/workflows/stale.yaml
- .github/workflows/test.yaml
This will reduce frequency of dependabot PRs.
Checklist:
> chore: change github actions to tags instead of latest SHAs

- lib/blueprinter/base.rb
- lib/blueprinter/reflection.rb
- spec/units/reflection_spec.rb
Initial attempt at a reflection API per #341. I've built a POC ActiveRecord automagic preloader against this and #358.
Blueprinter's native views and associations have been wrapped in simpler structs or classes, as the native ones made it pretty hard to get at stuff. Could also protect against internal changes in the future.
I exposed the internal `method` and `name` as `name` and `display_name` respectively, since Rubocop (and best practices) don't allow methods named "method".
```ruby
views = WidgetBlueprint.reflections
fields = views[:default].fields
fields[:name].name
=> :name
fields[:name].display_name
=> :name
assoc = views[:default].associations
assoc[:category].name
=> :category
assoc[:category].display_name
=> :category
assoc[:category].blueprint
=> CategoryBlueprint …
```
> Add reflection on views, fields, and associations

- lib/blueprinter.rb
- lib/blueprinter/base.rb
- lib/blueprinter/configuration.rb
- lib/blueprinter/extension.rb
- lib/blueprinter/extensions.rb
- spec/units/extensions_spec.rb
Initial attempt at a formal extension API as part of #341. I've built a POC ActiveRecord automagic preloader against this and #357.
In this proposal, an "extension" is a class inheriting from `Blueprinter::Extension` and passed to `Blueprinter.configure`. This PR defines only one extension method: `pre_render`. It intercepts whatever is passed to `.render` and returns (potentially) a modified result.
In the simplified version of my POC below, the extension figures out which associations to preload from the Blueprint view (using reflection), and returns the `ActiveRecord::Relation` with `preload` called.
```ruby
Blueprinter.configure do |config|
config.extensions << MyPreloadExtension.new
end
q = Widget.
where(...).
preload_blueprint
results = WidgetBlueprint.render(q)
class …
```
> Add extensions with initial support for pre_render

- lib/blueprinter/view_collection.rb
- spec/benchmarks/ips_test.rb
- spec/units/view_collection_spec.rb
While updating to the latest version, I've noticed that performance for rendering a blueprint with a transformer has worsened significantly. Digging around the code, I found that the issue is the usage of `concat` method which keeps adding and adding same transformers to the view on each call fetching defined transformers. This change is using simple array deconstructing to ensure immutability of the transformers array.
I've also added a case with a transformer to the basic benchmark spec because I think it's valuable to also have such a case there. Let me know if I need to make it more detailed or to also add it to other benchmark specs.
Checklist:
> Prevent re-adding same transformers to the view all the time

- CHANGELOG.md
- lib/blueprinter/version.rb
- Releases `1.0.1`, which includes:
- #381 
Checklist:
> Release v1.0.1

- .github/workflows/codeql.yaml
Adding custom codeQL configuration file so we can run code scans on PRs coming from forks. 
Checklist:
> Bdl codeql

- .github/workflows/test.yaml
Seems that GH has updated the `ubuntu-latest` image so that our deps for the 2.7 test runs no longer compile (as seen in recent PRs like #389). I pinned the 2.7 run to `ubuntu-20.04`, which seems to work.
There's a stuck "test (2.7)" job, but I'm hoping that's just some cached weirdness.
> Fix Ruby 2.7 in CI

- .github/workflows/test.yaml
> chore: make test github action workflow readonly

- lib/blueprinter/reflection.rb
- spec/units/reflection_spec.rb
This is a followup PR to #389, that fixes the problem at hand in a different (but more correct) way.
I ran into an issue with fields and categories that exist in the default view but are overridden in other views. Reflections seem to get overwritten by their definitions in the default view instead of the other view. This PR changes the behavior to key field and association reflections off of their `name` instead of their `method`, which the same way that Blueprinter uses when serializing data.
Checklist:
> Use field.name when building reflective views and associations

- CHANGELOG.md
- lib/blueprinter/version.rb
Create `1.0.2` release with this fix: https://github.com/procore-oss/blueprinter/pull/391
Checklist:
> Create 1.0.2 release

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/docs.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/question-support.yml
- CODE_OF_CONDUCT.md
- blueprinter.gemspec
You can find examples [here](https://github.com/procore-oss/oss-template/issues/new/choose)
- [Bug Issue](https://github.com/procore-oss/oss-template/issues/new?assignees=&labels=bug%2Cneeds-triage&projects=&template=bug.yml&title=%5Bbug%5D+%3Ctitle%3E)
- [Documentation Issue](https://github.com/procore-oss/oss-template/issues/new?assignees=&labels=docs%2Cneeds-triage&projects=&template=docs.yml&title=%5Bbug%5D+%3Ctitle%3E) 
- [Feature Issue](https://github.com/procore-oss/oss-template/issues/new?assignees=&labels=feature%2Cneeds-triage&projects=&template=feature-request.yml&title=%5BFeature+Request%5D+%3Ctitle%3E)
- [Question Issue](https://github.com/procore-oss/oss-template/issues/new?assignees=&labels=question%2Csupport%2Cneeds-triage&projects=&template=question-support.yml&title=%5BQu …
> chore: add github issue templates

- README.md
See the rendered updates at https://github.com/jhollinger/blueprinter/blob/ref-ext-docs/README.md.
Checklist:
> Docs for reflection and extensions

- .github/workflows/release.yaml
- .github/workflows/test.yaml
Move version file change check to its own job
allows us to simplify conditional checks to one
in other steps since they will be under their own
job now
Checklist:
> chore: simplify release GitHub Action

- CHANGELOG.md
See: https://github.com/procore-oss/blueprinter/issues/411
> Add note to 1.0.2 changelog about breaking change

- .github/dependabot.yaml
- .github/workflows/auto-assign-author.yaml
- .github/workflows/codeql.yaml
- .github/workflows/release.yaml
- .github/workflows/stale.yaml
- .github/workflows/test.yaml
- leave major dependency updates to their own PR so they stand out and are tested correctly
- prefix the PRs with `chore(deps)` to adhere to conventional commits
- Why?
- To prevent supply chain attack. Tags can move. They are mutable. SHAs are not.
- used [frizbee](https://github.com/stacklok/frizbee)
- ran `frizbee ghactions -d .github/workflows` locally
- also fixes formatting
Checklist:
> chore: group dependabot updates when minor/patch

- README.md
While learning how to use Blueprinter, I encountered some confusion with the current code examples. 
The concepts are well-explained, but there appears to be a discrepancy with the method names used in the examples. 
Checklist:
> docs: update Transform examples

- README.md
- lib/blueprinter/helpers/base_helpers.rb
- spec/integrations/base_spec.rb
- spec/integrations/shared/base_render_examples.rb
Closes https://github.com/procore-oss/blueprinter/issues/424
Checklist:
* [OK] I have updated the necessary documentation
* [OK] I have signed off all my commits as required by [DCO](https://github.com/procore-oss/blueprinter/blob/main/CONTRIBUTING.md)
* [OK] My build is green
> Feature: Discard nil value field

- bin/console
- lib/blueprinter/configuration.rb
- spec/spec_helper.rb
- spec/units/extensions_spec.rb
- spec/units/reflection_spec.rb
Checklist:
Fixes #443 
There's been a longstanding _implicit_ dependency on the standard `json` library, as `Blueprinter::Configuration` requires it to be available in the case where a separate JSON library isn't specified on configuration. This hasn't caused many issues in the past, as most use cases for `Blueprinter` are in environments where `json` is loaded (e.g. a Rails application). 
However, this is a brittle dependency, and if we're explicitly defining a default, we should make sure it's available in the confines of the class that needs it. 
- Explicitly `require 'json'` within `Blueprinter::Configuration`.
- Remove `require 'json'` from specs.
> Explicitly Require JSON Library

- Rakefile
- lib/blueprinter.rb
- lib/blueprinter/association.rb
- lib/blueprinter/base.rb
- lib/blueprinter/blueprint_validator.rb
- lib/blueprinter/configuration.rb
- lib/blueprinter/empty_types.rb
- lib/blueprinter/errors.rb
- lib/blueprinter/extractors/association_extractor.rb
- lib/blueprinter/extractors/auto_extractor.rb
- lib/blueprinter/extractors/block_extractor.rb
- lib/blueprinter/extractors/hash_extractor.rb
- lib/blueprinter/extractors/public_send_extractor.rb
- lib/blueprinter/helpers/base_helpers.rb
- lib/blueprinter/view_collection.rb
- spec/benchmarks/active_record_big_o_test.rb
- spec/benchmarks/active_record_ips_test.rb
- spec/benchmarks/big_o_test.rb
- spec/benchmarks/ips_test.rb
- spec/spec_helper.rb
- spec/units/association_spec.rb
- spec/units/blueprint_validator_spec.rb
- spec/units/configuration_spec.rb
- spec/units/date_time_formatter_spec.rb
- spec/units/deprecation_spec.rb
- spec/units/extensions_spec.rb
- spec/units/reflection_spec.rb
- spec/units/view_collection_spec.rb
Checklist:
Per #438, start using `autoload` for some things, and use `require 'blueprint/...` instead of `require_relative` in other places. This allows parts of the codebase to be loaded only if they're needed (Extensions, Transformers, V2, etc).
Based on feedback, the logic of `autoload` vs `require` is now:
- Use `autoload` for optional, top-level constants (`Base`, a future `V2`, `Extension`, `Transformer`, etc).
- Autoloaded files should `require` any constants they directly reference.
- Errors are an exception - we'll probably have an increasing number of them, so autoload makes IMHO.
- The above rules should ensure that nothing is autoloaded during render, except for errors.
> Use autoload instead of require/require_relative

- CHANGELOG.md
- lib/blueprinter/version.rb
Checklist:
- Releases `v1.1.0`.
> Release v1.1.0

- lib/blueprinter/association.rb
- lib/blueprinter/base.rb
- spec/integrations/base_spec.rb
- spec/integrations/shared/base_render_examples.rb
- spec/units/association_spec.rb
Checklist:
Fixes #458 
- Update interface for `Assocation.new` to differentiate between the `Blueprint` that the association will be rendered using, and the `Blueprint` that the association is defined within (`parent_blueprint`). This resolves an issue where a `Symbol` `if:` option would be sent to the association's `Blueprint` instead of the parent `Blueprint`. 
- Add tests to address coverage gap for this functionality.
> Fix Bug when using `if: Symbol` on Association

- lib/blueprinter/helpers/base_helpers.rb
- spec/integrations/base_spec.rb
Checklist:
Fixes #471 
- Falls back to `:default` if `options` hash contains a `view` key, but the value is "false-y". 
The test suite has become a bit of a mess, and I fear that we're introducing unintended regressions as a result. Will open an issue to try rework/restructure the tests.
> [Bug Fix] Fallback to :default view if nil is provided on reder

- lib/blueprinter/v2/dsl.rb
- spec/v2/partials_spec.rb
I've been thinking about an impendance mismatch between V1 and V2 that will make upgrading more difficult (whether manual or scripted). This is an attempt to patch over it without changing any of V2's semantics. Curious what everyone thinks.
Consider the following V1 Blueprint:
```ruby
class WidgetBlueprint < Blueprinter::Base
view :normal do
field :name
end
view :extended do
include_view :normal
field :description
end
end
```
There are currently two ways to represent this in V2: inheritance and partials.
```ruby
class WidgetBlueprint < Blueprinter::V2::Base
view :normal do
field :name
view :extended do
field :description
end
end
end
class WidgetBlueprint < Blueprinter::V2::Base
partial :normal do
field :name
end
view :normal do
use :normal
end
view :extended do
use :normal
field …
```
> Create an implicit partial for every V2 view

- README.md
- lib/blueprinter/rendering.rb
- spec/integrations/shared/base_render_examples.rb
The concept is simple, let's suppose there is a need of a custom object attribute, like:
```
view :default do
field :property do |object, options|
{ foo: 'foo'}.merge(options[:view] == :nested ? { foo2: 'foo2' } : {})
end
end
view :nested do
end
```
Currently there is no way to see which view triggered the field rendering, the PR simply add the exposition of the triggering view inside options, to avoid the need of conditional rendering based on view to duplicate the code (cause currently i need to define a duplication inside a view of the default view custom field)
Checklist:
> Feature: include original view in the options for custom field block
